name: PR Checks and Build
b/workflows/merge-check.yml@main
    secrets: inherit

  add-comments:
    if: github.event.pull_request.merged == true
    name: Add comment to Issues provided in PR description
    uses: CM0123/jira-integration0123/.github/workflows/comment-after-merge.yml@main
    secrets: inherit

